set SOL_DIR=%~1
set PLATFORM=%~2
set CONFIG=%~3
set DYNAMO_VERSION=%~4
set DYNAMO_INSTALL_VERSION=%~5

set SCRIPT_PACKAGE="%SOL_DIR%extras\prepareDynamoPackage.py"

py -3 %SCRIPT_PACKAGE% %PLATFORM% %CONFIG% %DYNAMO_VERSION% %DYNAMO_INSTALL_VERSION%

